
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Artifacts
{ 
    public enum ID
    {
        FireTrailDuration = 1,
        FireTrailSize = 2,
        FireTrailUptime = 3,
        SplitCount = 4,
        SplitSize = 5,
        Splitfire = 6,
        StenSpeed = 7,
        IceSize = 8,
        IceAtk = 9,
        LightningSize = 10,
        LightningFrequency = 11,
        LightingReq = 12,
        Invester = 13,
        Headhunter = 14,
        Stargate = 15,
    }

} 

