
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ArtifactParam : Luban.BeanBase
{
    public ArtifactParam(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["ArtifactName"].IsString) { throw new SerializationException(); }  ArtifactName = _buf["ArtifactName"]; }
        { if(!_buf["ArtifactPrice"].IsNumber) { throw new SerializationException(); }  ArtifactPrice = _buf["ArtifactPrice"]; }
        { if(!_buf["BallRelation"].IsString) { throw new SerializationException(); }  BallRelation = _buf["BallRelation"]; }
        { if(!_buf["ArtifactDes"].IsString) { throw new SerializationException(); }  ArtifactDes = _buf["ArtifactDes"]; }
        { if(!_buf["ArtifactType1"].IsString) { throw new SerializationException(); }  ArtifactType1 = _buf["ArtifactType1"]; }
        { if(!_buf["ArtifactStat1"].IsNumber) { throw new SerializationException(); }  ArtifactStat1 = _buf["ArtifactStat1"]; }
        { if(!_buf["ArtifactType2"].IsString) { throw new SerializationException(); }  ArtifactType2 = _buf["ArtifactType2"]; }
        { if(!_buf["ArtifactStat2"].IsNumber) { throw new SerializationException(); }  ArtifactStat2 = _buf["ArtifactStat2"]; }
        { if(!_buf["ArtifactType3"].IsString) { throw new SerializationException(); }  ArtifactType3 = _buf["ArtifactType3"]; }
        { if(!_buf["ArtifactStat3"].IsNumber) { throw new SerializationException(); }  ArtifactStat3 = _buf["ArtifactStat3"]; }
        { if(!_buf["AritfactIcon"].IsString) { throw new SerializationException(); }  AritfactIcon = _buf["AritfactIcon"]; }
    }

    public static ArtifactParam DeserializeArtifactParam(JSONNode _buf)
    {
        return new ArtifactParam(_buf);
    }

    public readonly int Id;
    public readonly string ID;
    public readonly string ArtifactName;
    public readonly int ArtifactPrice;
    public readonly string BallRelation;
    public readonly string ArtifactDes;
    public readonly string ArtifactType1;
    public readonly int ArtifactStat1;
    public readonly string ArtifactType2;
    public readonly int ArtifactStat2;
    public readonly string ArtifactType3;
    public readonly int ArtifactStat3;
    public readonly string AritfactIcon;
   
    public const int __ID__ = 1430726075;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ID:" + ID + ","
        + "ArtifactName:" + ArtifactName + ","
        + "ArtifactPrice:" + ArtifactPrice + ","
        + "BallRelation:" + BallRelation + ","
        + "ArtifactDes:" + ArtifactDes + ","
        + "ArtifactType1:" + ArtifactType1 + ","
        + "ArtifactStat1:" + ArtifactStat1 + ","
        + "ArtifactType2:" + ArtifactType2 + ","
        + "ArtifactStat2:" + ArtifactStat2 + ","
        + "ArtifactType3:" + ArtifactType3 + ","
        + "ArtifactStat3:" + ArtifactStat3 + ","
        + "AritfactIcon:" + AritfactIcon + ","
        + "}";
    }
}
}

