
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BallParam : Luban.BeanBase
{
    public BallParam(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["BallAttack"].IsNumber) { throw new SerializationException(); }  BallAttack = _buf["BallAttack"]; }
        { if(!_buf["BallCritChance"].IsNumber) { throw new SerializationException(); }  BallCritChance = _buf["BallCritChance"]; }
        { if(!_buf["BallCritDmg"].IsNumber) { throw new SerializationException(); }  BallCritDmg = _buf["BallCritDmg"]; }
        { if(!_buf["BallSpd"].IsNumber) { throw new SerializationException(); }  BallSpd = _buf["BallSpd"]; }
        { if(!_buf["BallSize"].IsNumber) { throw new SerializationException(); }  BallSize = _buf["BallSize"]; }
        { if(!_buf["BallSkillReq"].IsNumber) { throw new SerializationException(); }  BallSkillReq = _buf["BallSkillReq"]; }
        { if(!_buf["BallSkillID"].IsString) { throw new SerializationException(); }  BallSkillID = _buf["BallSkillID"]; }
        { if(!_buf["BallPrice"].IsNumber) { throw new SerializationException(); }  BallPrice = _buf["BallPrice"]; }
        { if(!_buf["BallShopChance"].IsNumber) { throw new SerializationException(); }  BallShopChance = _buf["BallShopChance"]; }
        { if(!_buf["AssetID"].IsString) { throw new SerializationException(); }  AssetID = _buf["AssetID"]; }
        { if(!_buf["BallDesc"].IsString) { throw new SerializationException(); }  BallDesc = _buf["BallDesc"]; }
        { if(!_buf["BallIcon"].IsString) { throw new SerializationException(); }  BallIcon = _buf["BallIcon"]; }
    }

    public static BallParam DeserializeBallParam(JSONNode _buf)
    {
        return new BallParam(_buf);
    }

    public readonly string ID;
    public readonly int BallAttack;
    public readonly float BallCritChance;
    public readonly float BallCritDmg;
    public readonly float BallSpd;
    public readonly float BallSize;
    public readonly int BallSkillReq;
    public readonly string BallSkillID;
    public readonly int BallPrice;
    public readonly int BallShopChance;
    public readonly string AssetID;
    public readonly string BallDesc;
    public readonly string BallIcon;
   
    public const int __ID__ = -1544017490;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BallAttack:" + BallAttack + ","
        + "BallCritChance:" + BallCritChance + ","
        + "BallCritDmg:" + BallCritDmg + ","
        + "BallSpd:" + BallSpd + ","
        + "BallSize:" + BallSize + ","
        + "BallSkillReq:" + BallSkillReq + ","
        + "BallSkillID:" + BallSkillID + ","
        + "BallPrice:" + BallPrice + ","
        + "BallShopChance:" + BallShopChance + ","
        + "AssetID:" + AssetID + ","
        + "BallDesc:" + BallDesc + ","
        + "BallIcon:" + BallIcon + ","
        + "}";
    }
}
}

