
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MilestoneParam : Luban.BeanBase
{
    public MilestoneParam(JSONNode _buf) 
    {
        { if(!_buf["MilestoneReq"].IsNumber) { throw new SerializationException(); }  MilestoneReq = _buf["MilestoneReq"]; }
        { if(!_buf["MonHPInc"].IsNumber) { throw new SerializationException(); }  MonHPInc = _buf["MonHPInc"]; }
        { if(!_buf["MonPointInc"].IsNumber) { throw new SerializationException(); }  MonPointInc = _buf["MonPointInc"]; }
        { if(!_buf["TerPointInc"].IsNumber) { throw new SerializationException(); }  TerPointInc = _buf["TerPointInc"]; }
        { if(!_buf["MonsterCount"].IsNumber) { throw new SerializationException(); }  MonsterCount = _buf["MonsterCount"]; }
    }

    public static MilestoneParam DeserializeMilestoneParam(JSONNode _buf)
    {
        return new MilestoneParam(_buf);
    }

    public readonly int MilestoneReq;
    public readonly float MonHPInc;
    public readonly float MonPointInc;
    public readonly float TerPointInc;
    public readonly float MonsterCount;
   
    public const int __ID__ = 589185309;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "MilestoneReq:" + MilestoneReq + ","
        + "MonHPInc:" + MonHPInc + ","
        + "MonPointInc:" + MonPointInc + ","
        + "TerPointInc:" + TerPointInc + ","
        + "MonsterCount:" + MonsterCount + ","
        + "}";
    }
}
}

