
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MonsterParam : Luban.BeanBase
{
    public MonsterParam(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Collision"].IsBoolean) { throw new SerializationException(); }  Collision = _buf["Collision"]; }
        { if(!_buf["MonsterHealth"].IsNumber) { throw new SerializationException(); }  MonsterHealth = _buf["MonsterHealth"]; }
        { if(!_buf["MonsterPoint"].IsNumber) { throw new SerializationException(); }  MonsterPoint = _buf["MonsterPoint"]; }
        { if(!_buf["MonsterDrop"].IsNumber) { throw new SerializationException(); }  MonsterDrop = _buf["MonsterDrop"]; }
        { if(!_buf["Asset ID"].IsString) { throw new SerializationException(); }  Asset ID = _buf["Asset ID"]; }
    }

    public static MonsterParam DeserializeMonsterParam(JSONNode _buf)
    {
        return new MonsterParam(_buf);
    }

    public readonly string ID;
    public readonly bool Collision;
    public readonly int MonsterHealth;
    public readonly int MonsterPoint;
    public readonly int MonsterDrop;
    public readonly string Asset ID;
   
    public const int __ID__ = 702549235;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Collision:" + Collision + ","
        + "MonsterHealth:" + MonsterHealth + ","
        + "MonsterPoint:" + MonsterPoint + ","
        + "MonsterDrop:" + MonsterDrop + ","
        + "Asset ID:" + Asset ID + ","
        + "}";
    }
}
}

