
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Person : Luban.BeanBase
{
    public Person(JSONNode _buf) 
    {
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["age"].IsNumber) { throw new SerializationException(); }  Age = _buf["age"]; }
        { if(!_buf["sex"].IsBoolean) { throw new SerializationException(); }  Sex = _buf["sex"]; }
    }

    public static Person DeserializePerson(JSONNode _buf)
    {
        return new Person(_buf);
    }

    public readonly string Name;
    public readonly int Age;
    public readonly bool Sex;
   
    public const int __ID__ = -1907849355;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "age:" + Age + ","
        + "sex:" + Sex + ","
        + "}";
    }
}
}

