
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class StoryParam : Luban.BeanBase
{
    public StoryParam(JSONNode _buf) 
    {
        { if(!_buf["Index"].IsNumber) { throw new SerializationException(); }  Index = _buf["Index"]; }
        { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["Text"].IsString) { throw new SerializationException(); }  Text = _buf["Text"]; }
    }

    public static StoryParam DeserializeStoryParam(JSONNode _buf)
    {
        return new StoryParam(_buf);
    }

    public readonly int Index;
    public readonly string Title;
    public readonly string Text;
   
    public const int __ID__ = -821404488;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "Title:" + Title + ","
        + "Text:" + Text + ","
        + "}";
    }
}
}

