
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbArtifactParam
{
    private readonly System.Collections.Generic.Dictionary<string, ArtifactParam> _dataMap;
    private readonly System.Collections.Generic.List<ArtifactParam> _dataList;
    
    public TbArtifactParam(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, ArtifactParam>(count);
        _dataList = new System.Collections.Generic.List<ArtifactParam>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ArtifactParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ArtifactParam.DeserializeArtifactParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ArtifactParam> DataMap => _dataMap;
    public System.Collections.Generic.List<ArtifactParam> DataList => _dataList;

    public ArtifactParam GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ArtifactParam Get(string key) => _dataMap[key];
    public ArtifactParam this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

