
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbMonsterParam
{
    private readonly System.Collections.Generic.Dictionary<string, MonsterParam> _dataMap;
    private readonly System.Collections.Generic.List<MonsterParam> _dataList;
    
    public TbMonsterParam(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, MonsterParam>(count);
        _dataList = new System.Collections.Generic.List<MonsterParam>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            MonsterParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.MonsterParam.DeserializeMonsterParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, MonsterParam> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterParam> DataList => _dataList;

    public MonsterParam GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MonsterParam Get(string key) => _dataMap[key];
    public MonsterParam this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

