
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPerson
{
    private readonly System.Collections.Generic.Dictionary<string, Person> _dataMap;
    private readonly System.Collections.Generic.List<Person> _dataList;
    
    public TbPerson(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Person>(count);
        _dataList = new System.Collections.Generic.List<Person>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Person _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Person.DeserializePerson(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Person> DataMap => _dataMap;
    public System.Collections.Generic.List<Person> DataList => _dataList;

    public Person GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Person Get(string key) => _dataMap[key];
    public Person this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

