
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbStoryParam
{
    private readonly System.Collections.Generic.Dictionary<int, StoryParam> _dataMap;
    private readonly System.Collections.Generic.List<StoryParam> _dataList;
    
    public TbStoryParam(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, StoryParam>(count);
        _dataList = new System.Collections.Generic.List<StoryParam>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StoryParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.StoryParam.DeserializeStoryParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StoryParam> DataMap => _dataMap;
    public System.Collections.Generic.List<StoryParam> DataList => _dataList;

    public StoryParam GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StoryParam Get(int key) => _dataMap[key];
    public StoryParam this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

