
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTerrainParam
{
    private readonly System.Collections.Generic.Dictionary<int, TerrainParam> _dataMap;
    private readonly System.Collections.Generic.List<TerrainParam> _dataList;
    
    public TbTerrainParam(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, TerrainParam>(count);
        _dataList = new System.Collections.Generic.List<TerrainParam>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TerrainParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TerrainParam.DeserializeTerrainParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Bumper, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TerrainParam> DataMap => _dataMap;
    public System.Collections.Generic.List<TerrainParam> DataList => _dataList;

    public TerrainParam GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TerrainParam Get(int key) => _dataMap[key];
    public TerrainParam this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

