
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TerrainParam : Luban.BeanBase
{
    public TerrainParam(JSONNode _buf) 
    {
        { if(!_buf["Bumper"].IsNumber) { throw new SerializationException(); }  Bumper = _buf["Bumper"]; }
        { if(!_buf["Spinner"].IsNumber) { throw new SerializationException(); }  Spinner = _buf["Spinner"]; }
        { if(!_buf["SpinnerMulti"].IsNumber) { throw new SerializationException(); }  SpinnerMulti = _buf["SpinnerMulti"]; }
        { if(!_buf["SpinnerCooldown"].IsNumber) { throw new SerializationException(); }  SpinnerCooldown = _buf["SpinnerCooldown"]; }
        { if(!_buf["DropSwitch"].IsNumber) { throw new SerializationException(); }  DropSwitch = _buf["DropSwitch"]; }
        { if(!_buf["BossDamager"].IsNumber) { throw new SerializationException(); }  BossDamager = _buf["BossDamager"]; }
        { if(!_buf["PortalEnter"].IsNumber) { throw new SerializationException(); }  PortalEnter = _buf["PortalEnter"]; }
        { if(!_buf["SmokeClearer"].IsNumber) { throw new SerializationException(); }  SmokeClearer = _buf["SmokeClearer"]; }
    }

    public static TerrainParam DeserializeTerrainParam(JSONNode _buf)
    {
        return new TerrainParam(_buf);
    }

    public readonly int Bumper;
    public readonly int Spinner;
    public readonly float SpinnerMulti;
    public readonly int SpinnerCooldown;
    public readonly int DropSwitch;
    public readonly int BossDamager;
    public readonly int PortalEnter;
    public readonly int SmokeClearer;
   
    public const int __ID__ = -490921352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Bumper:" + Bumper + ","
        + "Spinner:" + Spinner + ","
        + "SpinnerMulti:" + SpinnerMulti + ","
        + "SpinnerCooldown:" + SpinnerCooldown + ","
        + "DropSwitch:" + DropSwitch + ","
        + "BossDamager:" + BossDamager + ","
        + "PortalEnter:" + PortalEnter + ","
        + "SmokeClearer:" + SmokeClearer + ","
        + "}";
    }
}
}

