
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UpgradeParam : Luban.BeanBase
{
    public UpgradeParam(JSONNode _buf) 
    {
        { if(!_buf["UpdrageLevel"].IsNumber) { throw new SerializationException(); }  UpdrageLevel = _buf["UpdrageLevel"]; }
        { if(!_buf["UpgradeAtk"].IsNumber) { throw new SerializationException(); }  UpgradeAtk = _buf["UpgradeAtk"]; }
        { if(!_buf["UpgradeSpd"].IsNumber) { throw new SerializationException(); }  UpgradeSpd = _buf["UpgradeSpd"]; }
        { if(!_buf["UpgradeSize"].IsNumber) { throw new SerializationException(); }  UpgradeSize = _buf["UpgradeSize"]; }
        { if(!_buf["UpgradeCChance"].IsNumber) { throw new SerializationException(); }  UpgradeCChance = _buf["UpgradeCChance"]; }
        { if(!_buf["UpgradeCDmg"].IsNumber) { throw new SerializationException(); }  UpgradeCDmg = _buf["UpgradeCDmg"]; }
    }

    public static UpgradeParam DeserializeUpgradeParam(JSONNode _buf)
    {
        return new UpgradeParam(_buf);
    }

    public readonly int UpdrageLevel;
    public readonly float UpgradeAtk;
    public readonly float UpgradeSpd;
    public readonly float UpgradeSize;
    public readonly float UpgradeCChance;
    public readonly float UpgradeCDmg;
   
    public const int __ID__ = -1186999311;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UpdrageLevel:" + UpdrageLevel + ","
        + "UpgradeAtk:" + UpgradeAtk + ","
        + "UpgradeSpd:" + UpgradeSpd + ","
        + "UpgradeSize:" + UpgradeSize + ","
        + "UpgradeCChance:" + UpgradeCChance + ","
        + "UpgradeCDmg:" + UpgradeCDmg + ","
        + "}";
    }
}
}

